all:
	pdflatex Brian\ Goldman\ CV
	biber Brian\ Goldman\ CV
	pdflatex Brian\ Goldman\ CV
	pdflatex Brian\ Goldman\ CV
clean:
	rm -f *.log *.aux *.bbl *.blg *~ *.bcf *.out Brian\ Goldman\ CV.run.xml

extra_clean: clean
	rm -f Brian\ Goldman\ CV.pdf
